name: CI - Build and Push Docker Image

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          run: echo "$GITHUB_ACTOR"
          run: echo "$username"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          run: echo "$GITHUB_REPOSITORY_OWNER"
          tags: ghcr.io/${{ github.repository_owner }}/devsecops-demo:latest
