name: CI - Security Scan, Build and Push Docker Image

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep
        run: |
          mkdir -p .semgrep
          semgrep --config p/default --config .semgrep/ --sarif --output .semgrep/semgrep.sarif

      - name: Upload SARIF to GitHub
        if: always() # Always upload SARIF even if the workflow fails
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .semgrep/semgrep.sarif

      - name: Save Semgrep report
        if: always() # Always save Semgrep report even if the workflow fails
        run: semgrep --config auto --json > semgrep-report.json

      - name: Upload Semgrep report as artifact
        if: always() # Always upload Semgrep report even if the workflow fails
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json

  dependency-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          scan-type: "fs"
          scan-ref: .
          format: "sarif"
          output: "trivy-report.sarif"

      # Upload to Github Security Scan
      - name: Upload Trivy Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-report.sarif"

      # Run Trivy Image Scan
      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/devsecops-demo:latest"
          format: "sarif"
          output: "trivy-image-report.sarif"

      # Upload Trivy Image Report to Github Security Scan
      - name: Upload Trivy Image Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-image-report.sarif"

  build-and-push:
    runs-on: ubuntu-latest
    needs: security-scan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/devsecops-demo:latest
