name: CI - Build and Push Docker Image

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ----------------------
      # Semgrep security scan
      # ----------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan
        # run: semgrep --config auto --error   # Fails workflow if issues found
        run: semgrep --config auto  # Warning only if issues found

      - name: Save Semgrep report
        run: semgrep --config auto --json > semgrep-report.json

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v3
        with:
            name: semgrep-report
            path: semgrep-report.json

      # ----------------------
      # Build and Push Docker image
      # ----------------------
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/devsecops-demo:latest
