name: Semgrep SAST Scan

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep
        run: |
          mkdir -p .semgrep
          semgrep --config p/default --config .semgrep/ --sarif --output .semgrep/semgrep.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .semgrep/semgrep.sarif
